version: '3'

services:
    micanto:
        image: arinas/micanto:latest
        depends_on:
            - database
        ports:
            - 80:80
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=database
            - DB_USERNAME=micanto
            - DB_PASSWORD=yourpassword
            - DB_DATABASE=micanto
        volumes:
            - music:/music
            - img:/var/www/html/public/img
            - search_index:/var/www/html/storage/search-indexes

    database:
        image: mariadb:10.11
        volumes:
            - ./mariadb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=yourrootpassword
            - MYSQL_DATABASE=micanto
            - MYSQL_USER=micanto
            - MYSQL_PASSWORD=yourpassword

volumes:
    db:
        driver: local
    music:
        driver: local
    img:
        driver: local
    search_index:
        driver: local
